In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load the first dataframe which is the Books.csv file

books = pd.read_csv('../data/Books.csv',on_bad_lines='skip',encoding='latin-1')

C:\Users\Admin\AppData\Local\Temp\ipykernel_17760\1076595596.py:3: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('../data/Books.csv',on_bad_lines='skip',encoding='latin-1')

In [4]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [5]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='str')

In [6]:
books.iloc[3]['Image-URL-L']

'http://images.amazon.com/images/P/0374157065.01.LZZZZZZZ.jpg'

In [7]:
books.info()

<class 'pandas.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  str
 1   Book-Title           271360 non-null  str
 2   Book-Author          271358 non-null  str
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  str
 5   Image-URL-S          271360 non-null  str
 6   Image-URL-M          271360 non-null  str
 7   Image-URL-L          271357 non-null  str
dtypes: object(1), str(7)
memory usage: 16.6+ MB

In [8]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Image-URL-L', 'Publisher', 'Year-Of-Publication']]

In [9]:
books.head()

,ISBN,Book-Title,Book-Author,Image-URL-L,Publisher,Year-Of-Publication
0,0195153448,Classical Mythology,Mark P. O. Morford,http://images.amazon.com/images/P/0195153448.0...,Oxford University Press,2002
1,0002005018,Clara Callan,Richard Bruce Wright,http://images.amazon.com/images/P/0002005018.0...,HarperFlamingo Canada,2001
2,0060973129,Decision in Normandy,Carlo D'Este,http://images.amazon.com/images/P/0060973129.0...,HarperPerennial,1991
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,http://images.amazon.com/images/P/0374157065.0...,Farrar Straus Giroux,1999
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,http://images.amazon.com/images/P/0393045218.0...,W. W. Norton &amp; Company,1999

In [10]:
books.rename(columns={'Book-Title': 'Title', 
                    'Book-Author': 'Author',
                    'Image-URL-L': 'Image_URL',
                    'Year-Of-Publication': 'Year',
                    'Publisher': 'Publisher'
                      }, inplace=True)

In [11]:
books.head()

,ISBN,Title,Author,Image_URL,Publisher,Year
0,0195153448,Classical Mythology,Mark P. O. Morford,http://images.amazon.com/images/P/0195153448.0...,Oxford University Press,2002
1,0002005018,Clara Callan,Richard Bruce Wright,http://images.amazon.com/images/P/0002005018.0...,HarperFlamingo Canada,2001
2,0060973129,Decision in Normandy,Carlo D'Este,http://images.amazon.com/images/P/0060973129.0...,HarperPerennial,1991
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,http://images.amazon.com/images/P/0374157065.0...,Farrar Straus Giroux,1999
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,http://images.amazon.com/images/P/0393045218.0...,W. W. Norton &amp; Company,1999

In [12]:
## Now load the second dataframe which is the Users.csv file

users = pd.read_csv('../data/Users.csv',on_bad_lines='skip',encoding='latin-1')

In [13]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [14]:
users.rename(columns={'User-ID': 'User_ID',
                    'Location': 'Location',
                    'Age': 'Age'
                      }, inplace=True)

In [15]:
users.head()

   User_ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [16]:
# Load the third dataframe which is the Ratings.csv file

ratings = pd.read_csv('../data/Ratings.csv',on_bad_lines='skip',encoding='latin-1')

In [17]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [18]:
ratings.rename(columns={'User-ID': 'User_ID',
                    'ISBN': 'ISBN',
                    'Book-Rating': 'Rating'
                      }, inplace=True)

In [19]:
ratings.head()

   User_ID        ISBN  Rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [20]:
ratings['User_ID'].value_counts

<bound method IndexOpsMixin.value_counts of 0          276725
1          276726
2          276727
3          276729
4          276729
            ...
1149775    276704
1149776    276706
1149777    276709
1149778    276721
1149779    276723
Name: User_ID, Length: 1149780, dtype: int64>

In [21]:
# Users who had atleat given ratings to more than 200 books

x = ratings['User_ID'].value_counts() > 200

In [22]:
x

User_ID
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
276697    False
276706    False
276709    False
276721    False
276723    False
Name: count, Length: 105283, dtype: bool

In [23]:
x[x].shape

(899,)

In [24]:
index = x[x].index

In [25]:
index

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,   9856,  28634,  44296,  59727,  73681, 155916, 188951, 268622,
       274808],
      dtype='int64', name='User_ID', length=899)

In [26]:
ratings = ratings[ratings['User_ID'].isin(index)]

In [27]:
ratings.head()

      User_ID        ISBN  Rating
1456   277427  002542730X      10
1457   277427  0026217457       0
1458   277427  003008685X       8
1459   277427  0030615321       0
1460   277427  0060002050       0

In [28]:
# Now merge the ratings with the books 

ratings_with_books = ratings.merge(books, on='ISBN')

In [29]:
ratings_with_books.head()

,User_ID,ISBN,Rating,Title,Author,Image_URL,Publisher,Year
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,http://images.amazon.com/images/P/002542730X.0...,John Wiley &amp; Sons Inc,1994
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,http://images.amazon.com/images/P/0026217457.0...,John Wiley &amp; Sons,1995
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,http://images.amazon.com/images/P/003008685X.0...,Thomson Learning,1974
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,http://images.amazon.com/images/P/0030615321.0...,Henry Holt &amp; Co,1982
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,http://images.amazon.com/images/P/0060002050.0...,Avon Books,2002

In [30]:
number_of_ratings = ratings_with_books.groupby('Title')['Rating'].count().reset_index()

In [31]:
number_of_ratings.head()

                                               Title  Rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [32]:
number_of_ratings.rename(columns={'Rating': 'Number_of_Ratings'}, inplace=True)

In [33]:
number_of_ratings.head()

                                               Title  Number_of_Ratings
0   A Light in the Storm: The Civil War Diary of ...                  2
1                              Always Have Popsicles                  1
2               Apple Magic (The Collector's series)                  1
3   Beyond IBM: Leadership Marketing and Finance ...                  1
4   Clifford Visita El Hospital (Clifford El Gran...                  1

In [34]:
final_dataset = ratings_with_books.merge(number_of_ratings, on='Title')

In [35]:
final_dataset.head()

,User_ID,ISBN,Rating,Title,Author,Image_URL,Publisher,Year,Number_of_Ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,http://images.amazon.com/images/P/002542730X.0...,John Wiley &amp; Sons Inc,1994,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,http://images.amazon.com/images/P/0026217457.0...,John Wiley &amp; Sons,1995,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,http://images.amazon.com/images/P/003008685X.0...,Thomson Learning,1974,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,http://images.amazon.com/images/P/0030615321.0...,Henry Holt &amp; Co,1982,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,http://images.amazon.com/images/P/0060002050.0...,Avon Books,2002,13

In [36]:
# Lets find out those books which have atleast 50 ratings

final_dataset = final_dataset[final_dataset['Number_of_Ratings'] >= 50]

In [37]:
final_dataset.head()

,User_ID,ISBN,Rating,Title,Author,Image_URL,Publisher,Year,Number_of_Ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,http://images.amazon.com/images/P/002542730X.0...,John Wiley &amp; Sons Inc,1994,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,Perennial,1999,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,http://images.amazon.com/images/P/0060934417.0...,Perennial,2002,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,http://images.amazon.com/images/P/0061009059.0...,HarperTorch,1995,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,http://images.amazon.com/images/P/006440188X.0...,HarperTrophy,1998,79

In [38]:
# Drop the duplicates

final_dataset = final_dataset.drop_duplicates(subset=['User_ID', 'Title'], keep='first')

In [39]:
# Create a pivot table with the final dataset

pivot_table = final_dataset.pivot_table(columns='User_ID', index='Title', values='Rating')

In [40]:
pivot_table

User_ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
pivot_table.shape

(742, 888)

In [42]:
pivot_table.fillna(0, inplace=True)

User_ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
from scipy.sparse import csr_matrix

In [44]:
book_sparse_matrix = csr_matrix(pivot_table)

In [45]:
book_sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14961 stored elements and shape (742, 888)>

In [46]:
type(book_sparse_matrix)

scipy.sparse._csr.csr_matrix

In [47]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm = 'brute')

In [48]:
model.fit(book_sparse_matrix)

NearestNeighbors(algorithm='brute')

In [51]:
pivot_table.iloc[23]

User_ID
254       0.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
275970    0.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: A Thin Dark Line (Mysteries &amp; Horror), Length: 888, dtype: float64

In [52]:
distances, suggestions = model.kneighbors(pivot_table.iloc[23].values.reshape(1,-1), n_neighbors=6)

In [53]:
distances

array([[ 0.        , 26.75817632, 27.38612788, 28.17800561, 28.72281323,
        28.8444102 ]])

In [54]:
suggestions

array([[ 23, 184, 320, 372, 151, 536]])

In [56]:
for i in range(len(suggestions)):
    print(pivot_table.index[suggestions[i]])

Index(['A Thin Dark Line (Mysteries &amp; Horror)', 'Exclusive',
       'Long After Midnight', 'No Safe Place',
       'Deck the Halls (Holiday Classics)', 'The Cradle Will Fall'],
      dtype='str', name='Title')

In [57]:
# Store books name in a variable

books_name = pivot_table.index

In [58]:
books_name

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='str', name='Title', length=742)

In [59]:
final_dataset.head()

,User_ID,ISBN,Rating,Title,Author,Image_URL,Publisher,Year,Number_of_Ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,http://images.amazon.com/images/P/002542730X.0...,John Wiley &amp; Sons Inc,1994,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,Perennial,1999,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,http://images.amazon.com/images/P/0060934417.0...,Perennial,2002,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,http://images.amazon.com/images/P/0061009059.0...,HarperTorch,1995,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,http://images.amazon.com/images/P/006440188X.0...,HarperTrophy,1998,79

In [ ]:
np.where(pivot_table.index == 'The Lovely Bones: A Novel')[0][0]

(array([602]),)

In [65]:
# Final ratings ['title].value_couts()

ids = np.where(final_dataset['Title'] == 'The Lovely Bones: A Novel')[0][0]

In [66]:
final_dataset.iloc[ids]['Image_URL']

'http://images.amazon.com/images/P/0316666343.01.LZZZZZZZ.jpg'

In [67]:
books_name = []
for book_id in suggestions[0]:
    books_name.append(pivot_table.index[book_id])

In [68]:
books_name

['A Thin Dark Line (Mysteries &amp; Horror)',
 'Exclusive',
 'Long After Midnight',
 'No Safe Place',
 'Deck the Halls (Holiday Classics)',
 'The Cradle Will Fall']

In [73]:
ids_index = []
for name in books_name :
    ids = np.where(final_dataset['Title'] == name)[0][0]
    ids_index.append(ids)

In [74]:
ids_index

[np.int64(792),
 np.int64(786),
 np.int64(76),
 np.int64(22),
 np.int64(2583),
 np.int64(2297)]

In [75]:
for idx in ids_index:
    url = final_dataset.iloc[idx]['Image_URL']
    print(url)

http://images.amazon.com/images/P/0553571885.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0446604232.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0553571818.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0345404777.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0743418131.01.LZZZZZZZ.jpg
http://images.amazon.com/images/P/0440115450.01.LZZZZZZZ.jpg

In [76]:
books_name

['A Thin Dark Line (Mysteries &amp; Horror)',
 'Exclusive',
 'Long After Midnight',
 'No Safe Place',
 'Deck the Halls (Holiday Classics)',
 'The Cradle Will Fall']

In [78]:
final_dataset

,User_ID,ISBN,Rating,Title,Author,Image_URL,Publisher,Year,Number_of_Ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,http://images.amazon.com/images/P/002542730X.0...,John Wiley &amp; Sons Inc,1994,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,Perennial,1999,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,http://images.amazon.com/images/P/0060934417.0...,Perennial,2002,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,http://images.amazon.com/images/P/0061009059.0...,HarperTorch,1995,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,http://images.amazon.com/images/P/006440188X.0...,HarperTrophy,1998,79
...,...,...,...,...,...,...,...,...,...
487505,275970,1400031354,0,Tears of the Giraffe (No.1 Ladies Detective Ag...,Alexander McCall Smith,http://images.amazon.com/images/P/1400031354.0...,Anchor,2002,84
487506,275970,1400031362,0,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,http://images.amazon.com/images/P/1400031362.0...,Anchor,2002,60
487579,275970,1573229725,0,Fingersmith,Sarah Waters,http://images.amazon.com/images/P/1573229725.0...,Riverhead Books,2002,59
487618,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,http://images.amazon.com/images/P/1586210661.0...,Time Warner Audio Major,2001,146
487619,275970,1586212230,0,Naked,David Sedaris,http://images.amazon.com/images/P/1586212230.0...,Time Warner Audio Major,2001,53

In [79]:
pivot_table

User_ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [77]:
import pickle
pickle.dump(model, open('artifacts/model.pkl', 'wb'))
pickle.dump(books_name, open('artifacts/books_name.pkl', 'wb'))
pickle.dump(final_dataset, open('artifacts/final_dataset.pkl', 'wb'))
pickle.dump(pivot_table, open('artifacts/pivot_table.pkl', 'wb'))

## Testing Model

In [89]:
def recommend_books(book_name):

    book_id = np.where(pivot_table.index == book_name)[0][0]

    distances, suggestions = model.kneighbors(
        pivot_table.iloc[book_id].values.reshape(1, -1),
        n_neighbors=6
    )

    print(f"You searched: {book_name}\n")
    print("Suggested books:\n")

    for i in suggestions[0]:
        print(pivot_table.index[i])

In [90]:
books_name = "The Lovely Bones: A Novel"
recommend_books(books_name)

You searched: The Lovely Bones: A Novel

Suggested books:

The Lovely Bones: A Novel
The Bluest Eye
Dark Angel
Granny Dan
Nights in Rodanthe
Drowning Ruth (Oprah's Book Club)